[package]
name = "emotif___"
version = "1.0.0"
authors = ["Sean Batzel <romulus108@protonmail.com>", "Andrew Plaza <andrew.plaza@protonmail.com"]
build = "src/build.rs"

[dependencies]
colored = "1.5.2"
docopt = "0.8.1"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
peg = "0.5.4"

